version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - pip3 install boto3
      - export BUCKET=org.tommarx.lambda-deployment-artifacts
      - aws cloudformation package --template-file sam-deploy-demo/template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
